### ISSUE TITLE
Various Tricks to Optimize JS Code by Paul Ryan (Alligator) - Broken link

### ISSUE THREAD

**Issue by m1kc3b** [Aschen/understand-js-runtimes#3]
Hello,
The link above is broken.
Here is a new link :
https://www.digitalocean.com/community/tutorials/js-v8-engine

**Comment by Aschen** [comment]
I had this issue before, every link has it's own backup on internet archive.
Thanks for opening this issue thus ;) I hope you had useful reading here 
 
![image](https://user-images.githubusercontent.com/4447392/196200023-98e5b0f0-8ae7-4b6a-8661-a80400aa0f58.png)

**Comment by m1kc3b** [comment]
Thanks a lot 👍
